package domain;

public enum TypeLog
{
	CONNEXION_FAILED, // OK
	CONNEXION, // OK
	DECONNEXION, DEMANDE_SIGNATURE, // OK
	CHANGEMENT_SIGNATURE, // OK
	AJOUT_CLIENT, // OK
	SUPPRESSION_CLIENT, // OK
	AJOUT_DOCUMENT, // OK
	SUPPRESSION_DOCUMENT, // OK
	AJOUT_SIGNATURE, // OK
	
	//TODO
	ERREUR_LECTURE_CONFIGURATION,
	ERREUR_HASHBASE64,
	ERREUR_GETBLOB,
	ERROR_ENCODING_SIGNATURE,
	ERROR_RTIFACTORY,
	ERROR_ORIGINAL_METIER_FACTORY,
	ERROR_ENCODING_PDF_SIGZONE,
	ERROR_PDF2XML,
	ERROR_KEYNECTIS_KWEBSIGN,
	SIGNATURE_REUSSIE
	
	// Codes d'errerur dans la requete

}
