package domain;

public enum TypeLog
{
	CONNEXION_FAILED, // OK
	CONNEXION, // OK
	DECONNEXION, DEMANDE_SIGNATURE, // OK
	CHANGEMENT_SIGNATURE, // OK
	AJOUT_CLIENT, // OK
	SUPPRESSION_CLIENT, // OK
	AJOUT_DOCUMENT, // OK
	SUPPRESSION_DOCUMENT, // OK
	AJOUT_SIGNATURE // OK
	// Codes d'errerur dans la requete

}
