package domain;

public enum TypeLog
{
	CONNEXION_FAILED, // OK
	CONNEXION, // OK
	DECONNEXION, DEMANDE_SIGNATURE, // OK
	CHANGEMENT_SIGNATURE, // OK
	AJOUT_CLIENT, // OK
	SUPPRESSION_CLIENT, // OK
	AJOUT_DOCUMENT, // OK
	SUPPRESSION_DOCUMENT, // OK
	AJOUT_SIGNATURE, // OK
	
	//TODO
	ERREUR_LECTURE_CONFIGURATION,//OK
	ERREUR_HASHBASE64,//OK
	ERREUR_GETBLOB,//OK
	ERREUR_DECODING_BLOB_SIGNATURE,//OK
	ERREUR_RTIFACTORY,//OK
	ERREUR_ORIGINAL_METIER_FACTORY,//OK
	ERREUR_ENCODING_PDF_SIGZONE,//OK
	ERREUR_PDF2XML,//OK
	ERREUR_KEYNECTIS_KWEBSIGN,
	SIGNATURE_REUSSIE
	
	// Codes d'errerur dans la requete

}
